#!/usr/bin/env bash
# Start a 3-node local devnet at the Dijkstra era (PV11), which is required by
# Pebble's Value/array builtins (lookupCoin / unValueData / lengthOfArray) that
# are not available at Conway PV10.
#
# This reuses an environment previously generated by `cardano-testnet` (keys,
# topologies, genesis) under .devnet/data, edits the genesis/config to activate
# Dijkstra at epoch 0, wipes the chain DBs, and launches the 3 nodes directly
# with `cardano-node` (node1 = block producer, node2/node3 = relays) so they
# peer with each other and the Genesis state machine can leave "syncing".
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
D="$ROOT/.devnet/data"

echo ">> stopping any running nodes/testnet"
pkill -f "cardano-testnet" 2>/dev/null || true
ps aux | grep cardano-node | grep "$ROOT/.devnet" | grep -v grep | awk '{print $2}' | xargs -r kill 2>/dev/null || true
sleep 3

echo ">> patching genesis -> Dijkstra/PV11, fresh systemStart (byron + shelley consistent)"
SS=$(date -u -d '+25 seconds' +%Y-%m-%dT%H:%M:%SZ)
SS_POSIX=$(date -u -d "$SS" +%s)
node -e '
const fs=require("fs"), D=process.argv[1], ss=process.argv[2], posix=Number(process.argv[3]);
const sh=JSON.parse(fs.readFileSync(D+"/shelley-genesis.json"));
sh.systemStart=ss; sh.protocolParams.protocolVersion={major:11,minor:0};
fs.writeFileSync(D+"/shelley-genesis.json",JSON.stringify(sh,null,2));
// byron startTime (POSIX seconds) must match shelley systemStart
const by=JSON.parse(fs.readFileSync(D+"/byron-genesis.json"));
by.startTime=posix;
fs.writeFileSync(D+"/byron-genesis.json",JSON.stringify(by,null,2));
let cfg=JSON.parse(fs.readFileSync(D+"/configuration.yaml"));
cfg.ExperimentalHardForksEnabled=true;
cfg.TestDijkstraHardForkAtEpoch=0;
cfg["LastKnownBlockVersion-Major"]=11;
fs.writeFileSync(D+"/configuration.yaml",JSON.stringify(cfg,null,2));
' "$D" "$SS" "$SS_POSIX"
SHH=$(cardano-cli hash genesis-file --genesis "$D/shelley-genesis.json")
# Byron uses a different (canonical-CBOR) hashing scheme
BYH=$(cardano-cli byron genesis print-genesis-hash --genesis-json "$D/byron-genesis.json")
node -e 'const fs=require("fs"),D=process.argv[1];let c=JSON.parse(fs.readFileSync(D+"/configuration.yaml"));c.ShelleyGenesisHash=process.argv[2];c.ByronGenesisHash=process.argv[3];fs.writeFileSync(D+"/configuration.yaml",JSON.stringify(c,null,2));' "$D" "$SHH" "$BYH"
echo "   systemStart=$SS ($SS_POSIX) shelleyHash=$SHH byronHash=$BYH"

echo ">> wiping chain DBs"
rm -rf "$D"/node-data/node1/db "$D"/node-data/node2/db "$D"/node-data/node3/db
rm -f "$D"/socket/node1/sock "$D"/socket/node2/sock "$D"/socket/node3/sock

run_node() { # $1=node $2=port  (extra forging args via $3.. )
  local n="$1"; shift; local port="$1"; shift
  nohup cardano-node run \
    --config "$D/configuration.yaml" \
    --topology "$D/node-data/$n/topology.json" \
    --database-path "$D/node-data/$n/db" \
    --socket-path "$D/socket/$n/sock" \
    --port "$port" --host-addr 127.0.0.1 "$@" \
    > "$ROOT/.devnet/$n.log" 2>&1 &
  echo "   started $n (pid $!, port $port)"
}

echo ">> launching nodes"
run_node node2 36421
run_node node3 45809
run_node node1 38793 \
  --shelley-kes-key "$D/pools-keys/pool1/kes.skey" \
  --shelley-vrf-key "$D/pools-keys/pool1/vrf.skey" \
  --shelley-operational-certificate "$D/pools-keys/pool1/opcert.cert" \
  --byron-delegation-certificate "$D/pools-keys/pool1/byron-delegation.cert" \
  --byron-signing-key "$D/pools-keys/pool1/byron-delegate.key"

export CARDANO_NODE_SOCKET_PATH="$D/socket/node1/sock"
echo ">> waiting for blocks + Dijkstra era ..."
for i in $(seq 1 60); do
  sleep 3
  T=$(cardano-cli query tip --testnet-magic 42 2>/dev/null || true)
  [ -z "$T" ] && continue
  echo "$T" | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{try{const t=JSON.parse(d);console.log('   block',t.block,'era',t.era,'epoch',t.epoch,'sync',t.syncProgress)}catch(e){}})"
  echo "$T" | grep -q '"block": [1-9]' && echo "$T" | grep -qi "Dijkstra" && { echo ">> Dijkstra devnet is forging"; break; }
done
cardano-cli query protocol-parameters --testnet-magic 42 --out-file "$D/pparams.json" 2>/dev/null || true
node -e "const p=require('$D/pparams.json');console.log('   PV:',JSON.stringify(p.protocolVersion),'V3 cost params:',p.costModels.PlutusV3.length)" 2>/dev/null || true
